CNN 特点：
1） 局部连接
2） 权值共享

### conv2d

in_channels (int) – Number of channels in the input image

out_channels (int) – Number of channels produced by the convolution

kernel_size (int or tuple) – Size of the convolving kernel

stride (int or tuple, optional) – Stride of the convolution. Default: 1

<img src="https://tva1.sinaimg.cn/large/e6c9d24egy1h56ly3galkj20k20d8aaw.jpg" alt="image-20220814211842307" style="zoom:50%;" />

In [57]:
import torch
from torch import nn

kernel = nn.Conv2d(1, 1, 3)  # kernel_size=3
print(f'kernel.weight:\n {kernel.weight}\n \
kernel.bias:\n {kernel.bias}')
print(f'---'*20)
print(f'自定义新的权重值')
new_bias = torch.tensor([1.0])
kernel.bias=torch.nn.Parameter(new_bias) # 把Tensor的值作为权值赋值给Conv层，这里需要先转为torch.nn.Parameter类型，否则将报错
print(f'kernel.weight:\n {kernel.weight}\n \
kernel.bias:\n {kernel.bias}')
input = torch.randn(2, 1, 3, 4) # (batch, channel, h,w)
out = kernel(input)
out.shape, out

kernel.weight:
 Parameter containing:
tensor([[[[-0.2114,  0.0801, -0.2520],
          [-0.2688, -0.0469,  0.3085],
          [ 0.0192,  0.1497, -0.1336]]]], requires_grad=True)
 kernel.bias:
 Parameter containing:
tensor([-0.1365], requires_grad=True)
------------------------------------------------------------
自定义新的权重值
kernel.weight:
 Parameter containing:
tensor([[[[-0.2114,  0.0801, -0.2520],
          [-0.2688, -0.0469,  0.3085],
          [ 0.0192,  0.1497, -0.1336]]]], requires_grad=True)
 kernel.bias:
 Parameter containing:
tensor([1.], requires_grad=True)


(torch.Size([2, 1, 1, 2]),
 tensor([[[[1.1120, 0.5747]]],
 
 
         [[[1.0208, 1.2100]]]], grad_fn=<MkldnnConvolutionBackward>))

In [65]:
"""
一个卷积 demo， 来自百面深度学习p6
"""
import torch
from torch import nn

kernel = nn.Conv2d(1, 1, 3)  # kernel_size=3
new_bias = torch.tensor([0.0])
new_weight = torch.tensor([[[[ 0.0,  1,  2],
          [ 2,  2, 0],
          [0, 1,  2]]]])
kernel.bias=torch.nn.Parameter(new_bias)
kernel.weight=torch.nn.Parameter(new_weight)

input = torch.tensor([[[[3,3,2,1,0.0],
                       [0,0,1,3,1],
                        [3,1,2,2,3],
                        [2,0,0,2,2],
                        [2,0,0,0,1]
                       ]]])
out = kernel(input)
out.shape, out

(torch.Size([1, 1, 3, 3]),
 tensor([[[[12., 12., 17.],
           [10., 17., 19.],
           [ 9.,  6., 14.]]]], grad_fn=<ThnnConv2DBackward>))

### ConvMixer

![image-20221114225059224](https://tva1.sinaimg.cn/large/008vxvgGgy1h851m7os85j31om0huq7j.jpg)

In [7]:
# 常规卷积参数量：84， 分开后：42
import torch
import torch.nn as nn
conv_general = nn.Conv2d(3,3, 3, padding='same')  # 常规卷积

# ConvMixer
subconv_space_mixing = nn.Conv2d(3,3,3, groups=3, padding='same')  # 空间融合
subconv_channel_mixing = nn.Conv2d(3,3,1)  # point-wise卷积，通道融合
print(f'参数量统计：')
for p in conv_general.parameters():
    print(torch.numel(p))
print(f'-'*20)
for p in subconv_space_mixing.parameters():
    print(torch.numel(p))
for p in subconv_channel_mixing.parameters():
    print(torch.numel(p))

参数量统计：
81
3
--------------------
27
3
9
3
